---

- name: install nginx
  apt:
    pkg: '{{ item }}'
    state: present
  with_items:
    - nginx
  notify: start nginx

- name: disable default site
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

