- name: install pubkey for yarn
  become: yes
  apt_key:
    url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    state: present

- name: install stable yarn repo
  become: yes
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present
    update_cache: yes

- name: install yarn
  become: yes
  apt:
    name: yarn
    state: present

