---
# advanced package tool
- name: install apt transport https
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - python2.7
    - python2.7-minimal

- name: install apt system packages
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - python-simplejson
    - aptitude
    - fail2ban
    - unattended-upgrades
    - curl
    - unzip
    - ntp
    - acl

- name: install apt development tools packages
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - software-properties-common
    - python-software-properties
    - python-setuptools
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - python-pip
    - python-virtualenv
    - dialog
    - libaugeas0
    - ca-certificates

